# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 13:27
from __future__ import unicode_literals

from django.db import migrations
import social.apps.django_app.default.fields


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_auto_20160425_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocialauth',
            name='extra_data',
            field=social.apps.django_app.default.fields.JSONField(default={}),
        ),
    ]
